/**
 * HTML templates for PDF export via Gotenberg.
 * Use {{PLACEHOLDER}} syntax; replace in n8n Code node before PDF conversion.
 */

const RESUME_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: Arial, Helvetica, sans-serif; font-size: 11pt; line-height: 1.45; color: #111; margin: 40px; }
    h1 { font-size: 22pt; margin: 0 0 4px; }
    h2 { font-size: 12pt; text-transform: uppercase; border-bottom: 1px solid #333; margin: 18px 0 8px; padding-bottom: 2px; }
    .meta { color: #444; font-size: 10pt; margin-bottom: 14px; }
    ul { margin: 4px 0 8px 18px; padding: 0; }
    li { margin-bottom: 4px; }
    .role { font-weight: bold; }
    .period { float: right; font-weight: normal; color: #555; }
    p { margin: 6px 0; }
  </style>
</head>
<body>
{{RESUME_BODY}}
</body>
</html>`;

const COVER_LETTER_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: Arial, Helvetica, sans-serif; font-size: 11pt; line-height: 1.6; color: #111; margin: 40px; }
    .date { margin-bottom: 20px; color: #555; }
    p { margin: 0 0 12px; }
  </style>
</head>
<body>
  <div class="date">{{DATE}}</div>
  {{COVER_LETTER_BODY}}
</body>
</html>`;

const DAILY_EMAIL_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f4f4f5; margin: 0; padding: 24px; }
    .container { max-width: 680px; margin: 0 auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,.08); }
    .header { background: #0f172a; color: #fff; padding: 24px 28px; }
    .header h1 { margin: 0; font-size: 20px; }
    .header p { margin: 6px 0 0; opacity: .85; font-size: 14px; }
    .stats { display: flex; gap: 16px; padding: 16px 28px; background: #f8fafc; border-bottom: 1px solid #e2e8f0; }
    .stat { flex: 1; text-align: center; }
    .stat .num { font-size: 24px; font-weight: 700; color: #0f172a; }
    .stat .label { font-size: 12px; color: #64748b; }
    .job { padding: 20px 28px; border-bottom: 1px solid #e2e8f0; }
    .job:last-child { border-bottom: none; }
    .score { display: inline-block; background: #dcfce7; color: #166534; font-weight: 700; padding: 2px 10px; border-radius: 999px; font-size: 13px; }
    .score.low { background: #fef3c7; color: #92400e; }
    .company { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: .05em; }
    .title { font-size: 17px; font-weight: 600; margin: 4px 0; }
    .meta { font-size: 13px; color: #475569; margin-bottom: 8px; }
    .summary { font-size: 14px; color: #334155; line-height: 1.5; }
    .btn { display: inline-block; margin-top: 10px; background: #2563eb; color: #fff !important; text-decoration: none; padding: 8px 16px; border-radius: 8px; font-size: 13px; font-weight: 600; }
    .footer { padding: 16px 28px; font-size: 12px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>JobPilot AI — Daily Report</h1>
      <p>{{REPORT_DATE}} · Saudi Arabia & Remote opportunities</p>
    </div>
    <div class="stats">
      <div class="stat"><div class="num">{{TOTAL_JOBS}}</div><div class="label">Jobs Found</div></div>
      <div class="stat"><div class="num">{{QUALIFIED_JOBS}}</div><div class="label">Score ≥ 70</div></div>
      <div class="stat"><div class="num">{{LOW_MATCH_JOBS}}</div><div class="label">Low Match</div></div>
    </div>
    {{JOB_SECTIONS}}
    <div class="footer">Generated by JobPilot AI · n8n automation</div>
  </div>
</body>
</html>`;

function markdownToSimpleHtml(markdown) {
  return String(markdown || '')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[hul])/gm, (line) => (line.trim() ? `<p>${line}</p>` : ''));
}

function renderJobEmailSection(job) {
  const scoreClass = (job.matchScore || 0) >= 70 ? 'score' : 'score low';
  return `
    <div class="job">
      <span class="${scoreClass}">${job.matchScore || 0}% Match</span>
      <div class="company">${job.company}</div>
      <div class="title">${job.title}</div>
      <div class="meta">${job.location} · ${job.workType} · ${job.source}</div>
      <div class="summary">${job.matchSummary || job.summary || ''}</div>
      <a class="btn" href="${job.applyUrl}">View & Apply</a>
    </div>`;
}

module.exports = {
  RESUME_HTML,
  COVER_LETTER_HTML,
  DAILY_EMAIL_HTML,
  markdownToSimpleHtml,
  renderJobEmailSection,
};
